---
# tasks file for spigot
- name: install java (RedHat)
  package:
     name: java-11-openjdk
  when:  ansible_os_family == 'RedHat'

- name: install java (Debian)
  package:
     name: openjdk-11-jdk
  when:  ansible_os_family == 'Debian'

- name: install git
  package:
     name: git
  when:  ansible_os_family == 'RedHat'

- name: create minecraft admin user
  user:
    name: "{{ admin_username }}"
    comment: Minecraft Admin
    state: present
- block:
  - name: ansible create spigot directory
    file:
      path: "{{ spigot_dir }}"
      state: directory
  - name: ansible create minecraft server directory example
    file:
      path: "{{ spigot_dir }}/server/"
      state: directory
  - name: Download spigot buildtools
    get_url:
      url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      dest: "{{ spigot_dir }}/BuildTools.jar"
      owner: "{{ admin_username }}"
  - name: remove old spigot packages
    shell: rm -f "{{ spigot_dir }}/server/spigot*.jar"
    args:
      warn: false
  - name: building spigot tools
    command: "java -jar BuildTools.jar --rev latest --output-dir {{ spigot_dir }}/server"
    args:
        chdir: "{{ spigot_dir }}"
  - name: copy eula.txt
    copy:
      src: eula.txt
      dest: "{{ spigot_dir }}/server"
  - name: create ops
    template:
      src: ops.j2
      dest: "{{ spigot_dir }}/server/ops.json"
  - name: copy plugins
    copy:
      src: plugins
      dest: "{{ spigot_dir }}/server"
  - name: running server
    command: nohup java -Xms{{ gigs }}G -Xmx{{ gigs }}G -XX:+UseConcMarkSweepGC -jar spigot*.jar </dev/null >/dev/null 2>&1 &
    args:
      chdir: "{{ spigot_dir }}/server"

  - name: echo ops
    command: cat ops.json
    args:
      chdir: "{{ spigot_dir }}/server"
    register: results

  - debug:
      var: results
  become: yes
  become_user: "{{ admin_username }}"
